//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Boltpay.SDK.Models.Components
{
    using Boltpay.SDK.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Raw authorization response from the payment processor
    /// </summary>
    public class ProcessorResponse
    {

        [JsonProperty("content_type")]
        public string? ContentType { get; set; }

        [JsonProperty("api_version")]
        public string? ApiVersion { get; set; }

        [JsonProperty("text")]
        public string? Text { get; set; }
    }
}